name: IPTV Daily Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: '3.10'}
      - run: |
          pip install playwright requests
          playwright install chromium
      - run: python scraper.py
      - name: Read Link
        id: read_link
        run: echo "IPTV_URL=$(cat iptv_link.txt)" >> $GITHUB_ENV
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "Ddt42202@gmail.com"
          password: ${{ secrets.MY_EMAIL_PASSWORD }}
          subject: "🚀 الرابط الجديد وصل"
          to: "Ddt42202@gmail.com"
          from: "GitHub Robot"
          body: "هلا بك، هذا رابطك اليوم: ${{ env.IPTV_URL }}"
