name: IPTV Daily Update

on:
  schedule:
    - cron: '0 0 * * *' # يشتغل تلقائياً كل يوم الساعة 12 بالليل
  workflow_dispatch: # زر التشغيل اليدوي اللي ضغطت عليه قبل شوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run Scraper
        run: python scraper.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "Ddt42202@gmail.com"
          # هذا بيسحب الكود الأصفر اللي حطيته أنت في Secrets
          password: ${{ secrets.MY_EMAIL_PASSWORD }} 
          subject: "🚀 رابط الـ IPTV الجديد وصل يا بطل"
          to: "Ddt42202@gmail.com"
          from: "GitHub Robot 🤖"
          body: |
            يا هلا بصاحبي،
            
            "أطفالك" (الأكواد) قاموا بالواجب وحدثوا لك الرابط اليوم.
            تفضل بزيارة Firebase لمشاهدة الرابط الجديد أو تفقد لوحة التحكم.
            
            تم التحديث بنجاح!
