      - name: Run Scraper
        run: python scraper.py

      - name: Get Link from File
        id: read_file
        run: |
          LINK=$(cat iptv_link.txt)
          echo "FINAL_LINK=$LINK" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "Ddt42202@gmail.com"
          password: ${{ secrets.MY_EMAIL_PASSWORD }}
          subject: "🎁 رابط الـ IPTV الجديد وصل!"
          to: "Ddt42202@gmail.com"
          from: "GitHub Robot 🤖"
          body: |
            أبشر يا غالي، هذا هو الرابط الذي طلبه "أطفالك":
            
            ${{ env.FINAL_LINK }}
            
            مشاهدة ممتعة!
