name: Refresh Webtor Link
on:
  schedule:
    - cron: '*/30 * * * *' # يشتغل تلقائياً كل 30 دقيقة
  workflow_dispatch:      # زر للتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Run Bot
        run: node bot.js
