name: YouTube Sniper Bot

on:
  schedule:
    # سيقوم بالعمل تلقائياً كل 5 دقائق لفحص القناة
    - cron: '*/5 * * * *'
  workflow_dispatch: # يتيح لك تشغيله يدوياً متى شئت

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-oauthlib

      - name: Run Bot
        env:
          # هنا نربط الكود بالسر الذي وضعته في الخزنة
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python bot.py
