name: Update IPTV and Movies

on:
  schedule:
    - cron: '0 * * * *' # سيعمل البوت تلقائياً كل ساعة
  workflow_dispatch: # يتيح لك تشغيل البوت يدوياً بضغطة زر

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests playwright

      - name: Install Browser (for movies)
        run: playwright install chromium

      - name: Run Bot
        run: python bot.py
