name: Movie Randomizer Bot

on:
  schedule:
    - cron: '0 * * * *' # يعمل تلقائياً كل ساعة
  workflow_dispatch: # يتيح لك تشغيله يدوياً

jobs:
  update_movie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run Bot
        run: python bot.py
